configserver: true
bus: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.springbox-service-registry.credentials.uri:http://192.168.99.100:8761}/eureka/

zuul:
  routes:
    user:
      url: http://192.168.99.100:9999/uaa/user
spring:
  oauth2:
    client:
      accessTokenUri: http://192.168.99.100:9999/uaa/oauth/token
      userAuthorizationUri: http://192.168.99.100:9999/uaa/oauth/authorize
    resource:
          userInfoUri: http://192.168.99.100:9999/uaa/user
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: 192.168.99.100
  neo4j:
    host: 192.168.99.100
    port: 7474

---
spring:
  profiles: container-engine
  oauth2:
    client:
      accessTokenUri: http://auth-server:9999/uaa/oauth/token
      userAuthorizationUri: http://auth-server:9999/uaa/oauth/authorize
    resource:
          userInfoUri: http://auth-server:9999/uaa/user
  rabbitmq:
    host: rabbitmqsvc
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: mongodb
  neo4j:
    host: neo4j
    port: 7474

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

zuul:
  routes:
    user:
      url: http://auth-server:9999/uaa/user